import { BaseParser, ReportCategory } from "./BaseParser.js";
import { ReportData, LintIssue } from "../models/ReportData.js";

const LOCATION_PATTERN = /:(\d+):(\d+)\s*(?:-\s+)?(error|warning|hint)\s+/i;
const ASTRO_HEADER_PATTERNS = [
  /Getting diagnostics for Astro files/i,
  /Result \(\d+ files\)/i,
];
const ANSI_PATTERN = new RegExp(`${String.fromCharCode(27)}\\[[0-9;]*m`, "g");

/**
 * Parser for output generated by `astro check`
 */
export class AstroCheckParser extends BaseParser {
  canParse(_filePath, content) {
    if (!content) {
      return false;
    }

    const sanitized = this.#stripAnsi(content);
    if (LOCATION_PATTERN.test(sanitized)) {
      return true;
    }

    return ASTRO_HEADER_PATTERNS.some((pattern) => pattern.test(sanitized));
  }

  getPriority() {
    return 8;
  }

  getCategory() {
    return ReportCategory.LINT;
  }

  getAutoPatterns() {
    return [
      "**/astro-check.log",
      "**/astro-check.txt",
      "**/astro-check-report.log",
      "**/astro-check-report.txt",
    ];
  }

  parse(content) {
    const reportData = new ReportData();
    reportData.reportType = "lint";

    if (!content) {
      return reportData;
    }

    const sanitized = this.#stripAnsi(content);
    const lines = sanitized.split(/\r?\n/);

    for (const line of lines) {
      const issue = this.#parseDiagnosticLine(line);
      if (!issue) {
        continue;
      }

      reportData.addLintIssue(
        new LintIssue({
          ...issue,
          source: "astro-check",
        }),
      );
    }

    return reportData;
  }

  #parseDiagnosticLine(line) {
    if (!line || !line.trim()) {
      return null;
    }

    const locationMatch = line.match(LOCATION_PATTERN);
    if (!locationMatch || locationMatch.index === undefined) {
      return null;
    }

    const filePath = line.slice(0, locationMatch.index).trim();
    if (!filePath) {
      return null;
    }

    const lineNumber = Number(locationMatch[1]) || 0;
    const columnNumber = Number(locationMatch[2]) || 0;
    const severity = locationMatch[3].toLowerCase();

    const remainderStart = locationMatch.index + locationMatch[0].length;
    const remainder = line.slice(remainderStart).trim();

    let rule = "astro-check";
    let message = remainder;

    const ruleMatch = remainder.match(/^([A-Za-z]+\d+)\s*:\s*(.*)$/);
    if (ruleMatch) {
      rule = ruleMatch[1];
      message = ruleMatch[2].trim();
    }

    return {
      file: filePath,
      line: lineNumber,
      column: columnNumber,
      severity,
      rule,
      message,
    };
  }

  #stripAnsi(text) {
    return text.replace(ANSI_PATTERN, "");
  }
}
