name: "Get issue number"
description: "Action to get Pull request or issue number"
author: hoverkraft
branding:
  icon: hash
  color: blue

outputs:
  issue-number:
    description: "The issue number."
    value: ${{ steps.get-issue-number.outputs.issue-number }}

runs:
  using: "composite"
  steps:
    - id: get-issue-number
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const pullRequestNumber = context.payload.pull_request?.number;
          const issueNumber = context.payload.issue?.number;
          const result = pullRequestNumber ?? issueNumber;

          if (!result) {
            core.setFailed('No PR or issue number found for the current event');
            return;
          }

          core.setOutput('issue-number', result);
