version: 2
updates:
  - package-ecosystem: docker
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"

  - package-ecosystem: github-actions
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"

  - package-ecosystem: github-actions
    open-pull-requests-limit: 20
    directory: "/actions/**/action.yml"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
