name: "Create or update comment"
description: "Action to create or update comment in pull request or issue"
author: hoverkraft
branding:
  icon: message-square
  color: blue

inputs:
  title:
    description: "The comment title. Must be static and unique, will be used to retrieve the comment if exists already."
    required: true
  body:
    description: "The comment body. See [https://github.com/peter-evans/create-or-update-comment](https://github.com/peter-evans/create-or-update-comment)"
    required: false
  reactions:
    description: "A comma separated list of reactions to add to the comment. See [https://github.com/peter-evans/create-or-update-comment](https://github.com/peter-evans/create-or-update-comment)"
    required: false
  comment-author:
    description: "The comment author. Default is github-actions[bot]."
    required: false
    default: "github-actions[bot]"
  token:
    description: |
      Optional token to interact with GitHub API.
      If not defined or empty, the action will use the GITHUB_TOKEN provided by GitHub.
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: |
        [ -d ./self-actions ] || (mkdir -p ./self-actions/ && cp -r $GITHUB_ACTION_PATH/../* ./self-actions/)

    - id: get-issue-number
      uses: ./self-actions/get-issue-number

    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: |
        rm -fr ./self-actions

    - uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3.1.0
      id: find-comment
      with:
        issue-number: ${{ steps.get-issue-number.outputs.issue-number }}
        comment-author: ${{ inputs.comment-author }}
        body-includes: ${{ inputs.title }}
        token: ${{ inputs.token || github.token }}

    - uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
      with:
        edit-mode: replace
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ steps.get-issue-number.outputs.issue-number }}
        body: |
          ${{ inputs.title }}

          ${{ inputs.body }}
        reactions: ${{ inputs.reactions }}
        token: ${{ inputs.token || github.token }}
