name: "working directory"
description: "Action to resolve and validate a working directory path."
author: hoverkraft
branding:
  icon: folder
  color: blue

inputs:
  working-directory:
    description: "Relative or absolute working directory path to resolve."
    required: false
    default: "."
  enforce-path-in-workspace:
    description: "Whether to fail when the resolved path is outside GITHUB_WORKSPACE."
    required: false
    default: "true"

outputs:
  absolute-path:
    description: "The resolved absolute working directory path."
    value: ${{ steps.working-directory.outputs.absolute-path }}
  workspace-relative-path:
    description: "The resolved working directory path relative to GITHUB_WORKSPACE."
    value: ${{ steps.working-directory.outputs.workspace-relative-path }}

runs:
  using: "composite"
  steps:
    - id: working-directory
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        WORKING_DIRECTORY_INPUT: ${{ inputs.working-directory }}
        ENFORCE_PATH_IN_WORKSPACE_INPUT: ${{ inputs.enforce-path-in-workspace }}
      with:
        script: |
          const fs = require('node:fs');
          const path = require('node:path');
          const workspaceRoot = process.env.GITHUB_WORKSPACE || process.cwd();
          const enforcePathInWorkspace = (process.env.ENFORCE_PATH_IN_WORKSPACE_INPUT || 'true') !== 'false';

          let workingDirectory = process.env.WORKING_DIRECTORY_INPUT || '.';

          if (!path.isAbsolute(workingDirectory)) {
            workingDirectory = path.join(workspaceRoot, workingDirectory);
          }

          if (!fs.existsSync(workingDirectory)) {
            core.setFailed(`The specified working directory does not exist: ${workingDirectory}`);
            return;
          }

          if (!fs.statSync(workingDirectory).isDirectory()) {
            core.setFailed(`The specified working directory is not a directory: ${workingDirectory}`);
            return;
          }

          const absolutePath = path.resolve(workingDirectory);
          const workspaceRelativePath = path.relative(workspaceRoot, absolutePath) || '.';

          if (enforcePathInWorkspace) {
            const isOutsideWorkspace = workspaceRelativePath.startsWith('..') || path.isAbsolute(workspaceRelativePath);

            if (isOutsideWorkspace) {
              core.setFailed(`The specified working directory is outside GITHUB_WORKSPACE: ${absolutePath}`);
              return;
            }
          }

          core.setOutput('absolute-path', absolutePath);
          core.setOutput('workspace-relative-path', workspaceRelativePath);
