# Set matrix ouput in file to be uploaded as artifacts, because github action does not handle job outputs for matrix
# Workaround for https://github.com/orgs/community/discussions/26639

name: "Set matrix ouput"
description: "Set matrix ouput in file to be uploaded as artifacts, because GitHub Action does not handle job outputs for matrix."
author: Hoverkraft
branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  value:
    description: "The matrix output to set."
    required: true
  artifact-name:
    description: "The name of the artifact to upload."
    required: true
outputs:
  artifact-name:
    description: "The real unique name of the uploaded artifact."
    value: ${{ steps.prepare-upload.outputs.artifact-name }}

runs:
  using: "composite"
  steps:
    - id: prepare-upload
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const { join } = require('path');
          const { writeFileSync } = require('fs');
          const { randomUUID } = require('crypto');

          const artifactName = `${{ github.run_id }}-${{ github.run_number }}-${{ inputs.artifact-name }}`;
          core.setOutput("artifact-name", artifactName);

          const uniquid = randomUUID();
          const timestamp = Date.now();
          const artifactUniqueName = `${artifactName}-${timestamp}-${uniquid}`;
          core.setOutput("artifact-unique-name", artifactUniqueName);

          const artifactDirPath = join("/tmp",artifactUniqueName);
          await io.mkdirP(artifactDirPath);

          const artifactPath = join(artifactDirPath, `${artifactUniqueName}.json`);
          core.setOutput("artifact-path", artifactPath);
          writeFileSync(artifactPath, `${{ inputs.value }}`);

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ steps.prepare-upload.outputs.artifact-unique-name }}
        path: ${{ steps.prepare-upload.outputs.artifact-path }}
