# Set matrix ouput in file to be uploaded as artifacts, because github action does not handle job outputs for matrix
# Workaround for https://github.com/orgs/community/discussions/26639

name: "Set matrix ouput"
description: "Set matrix ouput in file to be uploaded as artifacts, because GitHub action does not handle job outputs for matrix"
author: Hoverkraft
branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  value:
    description: "The matrix output to set."
    required: true
  artifact-name:
    description: "The name of the artifact to upload."
    required: true
outputs:
  artifact-name:
    description: "The real unique name of the uploaded artifact."
    value: ${{ steps.prepare-upload.outputs.artifact-name }}

runs:
  using: "composite"
  steps:
    - id: prepare-upload
      uses: actions/github-script@v6
      with:
        script: |
          const { join } = require('path');
          const { existsSync, writeFileSync } = require('fs');
          const { randomUUID } = require('crypto');

          const artifactName = `${{ github.run_id }}-${{ github.run_number }}-${{ inputs.artifact-name }}`;
          core.setOutput("artifact-name", artifactName);

          const artifactPath = join("/tmp",artifactName);
          core.setOutput("artifact-path", artifactPath);
          await io.mkdirP(artifactPath);

          const maxAttempts = 10;
          let matrixOutputFile = '';
          for (let i = 1; i <= maxAttempts; i++) {
            const uniquid = randomUUID();
            const timestamp = Date.now();
            const matrixOutputFileName = `${timestamp}-${artifactName}-${uniquid}.json`;

            matrixOutputFile = join(artifactPath, matrixOutputFileName);
            if (!existsSync(matrixOutputFile)) {
              break;
            }
            matrixOutputFile = '';
          }

          if (!matrixOutputFile) {
            core.setFailed(`Failed to find unique file name after ${maxAttempts} attempts`);
          }

          writeFileSync(matrixOutputFile, `${{ inputs.value }}`);

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.prepare-upload.outputs.artifact-name }}
        path: ${{ steps.prepare-upload.outputs.artifact-path }}
