name: "Set matrix ouput"
description: |
  Set matrix ouput in file to be uploaded as artifacts, because GitHub Action does not handle job outputs for matrix.
  Workaround for https://github.com/orgs/community/discussions/26639.
author: hoverkraft
branding:
  icon: upload-cloud
  color: blue

inputs:
  value:
    description: "The matrix output to set."
    required: true
  artifact-name:
    description: "The name of the artifact to upload."
    required: true
outputs:
  artifact-name:
    description: "The real unique name of the uploaded artifact."
    value: ${{ steps.prepare-upload.outputs.artifact-name }}

runs:
  using: "composite"
  steps:
    - id: prepare-upload
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        ARTIFACT_NAME_INPUT: ${{ inputs.artifact-name }}
        MATRIX_VALUE: ${{ inputs.value }}
      with:
        script: |
          const { join } = require('path');
          const { writeFileSync } = require('fs');
          const { randomUUID } = require('crypto');

          const artifactName = `${process.env.GITHUB_RUN_ID}-${process.env.GITHUB_RUN_NUMBER}-${process.env.ARTIFACT_NAME_INPUT}`;
          core.setOutput("artifact-name", artifactName);

          const uniquid = randomUUID();
          const timestamp = Date.now();
          const artifactUniqueName = `${artifactName}-${timestamp}-${uniquid}`;
          core.setOutput("artifact-unique-name", artifactUniqueName);

          const artifactDirPath = join("/tmp",artifactUniqueName);
          await io.mkdirP(artifactDirPath);

          const artifactPath = join(artifactDirPath, `${artifactUniqueName}.json`);
          core.setOutput("artifact-path", artifactPath);
          writeFileSync(artifactPath, process.env.MATRIX_VALUE ?? "");

    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ steps.prepare-upload.outputs.artifact-unique-name }}
        path: ${{ steps.prepare-upload.outputs.artifact-path }}
