# Set matrix ouput in file to be uploaded as artifacts, because github action does not handle job outputs for matrix
# Workaround for https://github.com/orgs/community/discussions/26639

name: "Set matrix ouput"
description: "Set matrix ouput in file to be uploaded as artifacts, because GitHub action does not handle job outputs for matrix"
author: Hoverkraft
branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  value:
    description: "The matrix output to set."
    required: true
  artifact-name:
    description: "The name of the artifact to upload."
    required: true
outputs:
  artifact-name:
    description: "The real unique name of the uploaded artifact."
    value: ${{ steps.prepare-upload.outputs.artifact-name }}

runs:
  using: "composite"
  steps:
    - id: prepare-upload
      shell: bash
      run: |
        # Define a unique artifact name for the current workflow
        ARTIFACT_NAME="${{ github.run_id }}-${{ github.run_number }}-${{ inputs.artifact-name }}"
        echo "artifact-name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

        ARTIFACT_PATH="/tmp/$ARTIFACT_NAME"
        echo "artifact-path=$ARTIFACT_PATH" >> "$GITHUB_OUTPUT"
        mkdir -p "$ARTIFACT_PATH"

        MAX_ATTEMPTS=10
        MATRIX_OUTPUT_FILE=""
        for i in $(seq 1 $MAX_ATTEMPTS); do
          MATRIX_OUTPUT_FILE="$ARTIFACT_PATH/${{ inputs.artifact-name }}-$(uuidgen).json"
          if [ ! -f "$MATRIX_OUTPUT_FILE" ]; then
            break
          fi
          MATRIX_OUTPUT_FILE=""
        done
        if [ -z "$MATRIX_OUTPUT_FILE" ]; then
          echo "Failed to find unique file name after $MAX_ATTEMPTS attempts"
          exit 1
        fi

        echo '${{ inputs.value }}' > "$MATRIX_OUTPUT_FILE"

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.prepare-upload.outputs.artifact-name }}
        path: ${{ steps.prepare-upload.outputs.artifact-path }}
