name: "Checkout"
description: |
  Action to checkout the repository compatible for PRs, issues and push events.
  Workaround for https://github.com/actions/checkout/issues/331](https://github.com/actions/checkout/issues/331.
author: hoverkraft
branding:
  icon: git-branch
  color: blue

inputs:
  fetch-depth:
    description: |
      Number of commits to fetch. 0 indicates all history for all branches and tags.
      See https://github.com/actions/checkout#usage
    default: "1"
  lfs:
    description: |
      Whether to download Git-LFS files.
      See https://github.com/actions/checkout#usage
    default: "false"
  persist-credentials:
    description: |
      Whether to persist the token credentials in the Git config.
      Default to false for security reasons.
      See https://github.com/orgs/community/discussions/179107.
    default: "false"
  token:
    description: |
      Token to use for checking out the repository instead of the default GITHUB_TOKEN.
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      if: github.event_name == 'issue_comment'
      with:
        ref: refs/pull/${{ github.event.issue.number }}/head
        fetch-depth: ${{ inputs.fetch-depth }}
        lfs: ${{ inputs.lfs }}
        token: ${{ inputs.token || github.token }}
        persist-credentials: ${{ inputs.persist-credentials == 'true' && 'true' || 'false' }}

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      if: github.event_name != 'issue_comment'
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        lfs: ${{ inputs.lfs }}
        token: ${{ inputs.token || github.token }}
        persist-credentials: ${{ inputs.persist-credentials == 'true' && 'true' || 'false' }}
