name: "Repository owner is organization"
description: "Action to check if the repository owner is an organization."
author: hoverkraft
branding:
  icon: users
  color: blue

inputs:
  github-token:
    description: "GitHub token for fetching users API."
    default: ${{ github.token }}
    required: false

outputs:
  is-organization:
    description: "The boolean value indicating if the repository owner is an organization."
    value: "${{ steps.check-org.outputs.is-organization }}"

runs:
  using: "composite"
  steps:
    - id: check-org
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const owner = context.repo.owner;
          const { data } = await github.rest.users.getByUsername({ username: owner });
          const isOrganization = (data?.type ?? '').toLowerCase() === 'organization';
          if (isOrganization) {
            core.setOutput('is-organization', true);
          }
