name: "Get matrix ouput"
description: |
  Download matrix ouputs from artifacts, because GitHub Action does not handle job outputs for matrix.
  Workaround for https://github.com/orgs/community/discussions/26639.
author: hoverkraft
branding:
  icon: download-cloud
  color: blue

inputs:
  artifact-name:
    description: "The name of the artifact to download."
    required: true
  remove-artifact:
    description: "Define weather to remove the downloaded artifact after reading."
    required: false
    default: "true"
outputs:
  result:
    description: "The matrix combined JSON outputs."
    value: ${{ steps.read-artifacts.outputs.artifacts }}

runs:
  using: "composite"
  steps:
    - id: prepare-download
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        ARTIFACT_NAME_INPUT: ${{ inputs.artifact-name }}
      with:
        script: |
          const path = require('node:path');
          const runId = process.env.GITHUB_RUN_ID ?? '';
          const runNumber = process.env.GITHUB_RUN_NUMBER ?? '';
          const artifactNameInput = process.env.ARTIFACT_NAME_INPUT ?? '';

          // Forge the unique artifact name for the current workflow
          const artifactName = `${runId}-${runNumber}-${artifactNameInput}`;
          core.setOutput('artifact-name', artifactName);

          const artifactPath = path.join(process.env.RUNNER_TEMP, artifactName);
          core.setOutput('artifact-path', artifactPath);

    - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        path: ${{ steps.prepare-download.outputs.artifact-path }}
        pattern: ${{ steps.prepare-download.outputs.artifact-name }}-*
        merge-multiple: true

    - id: read-artifacts
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        ARTIFACT_PATH: ${{ steps.prepare-download.outputs.artifact-path }}
        REMOVE_ARTIFACT: ${{ inputs.remove-artifact }}
      with:
        script: |
          const { readFileSync } = require('fs');

          const artifactPath = process.env.ARTIFACT_PATH;
          const globber = await glob.create(`${artifactPath}/*.json`, {followSymbolicLinks: false});
          const artifactFiles = await globber.glob();

          core.debug(`Found ${artifactFiles.length} files in ${artifactPath}`);

          const result = artifactFiles
            .map(file => readFileSync(file, 'utf8').trim())
            .filter(content => content)
            .join(",");

          core.setOutput('artifacts',`[${result}]`);

          const shouldRemoveArtifact = (process.env.REMOVE_ARTIFACT || '').toLowerCase() === 'true';
          if(shouldRemoveArtifact) {
            await io.rmRF(artifactPath);
          }

    - if: ${{ inputs.remove-artifact == 'true' }}
      uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
      with:
        name: ${{ steps.prepare-download.outputs.artifact-name }}-*
