# Download matrix ouputs from artifacts, because github action does not handle job outputs for matrix
# Workaround for https://github.com/orgs/community/discussions/26639

name: "Get matrix ouput"
description: "Download matrix ouputs from artifacts, because GitHub action does not handle job outputs for matrix"
author: Hoverkraft
branding:
  icon: download-cloud
  color: gray-dark

inputs:
  artifact-name:
    description: "The name of the artifact to download."
    required: true
  remove-artifact:
    description: "Define weather to remove the downloaded artifact after reading."
    required: false
    default: "true"
outputs:
  result:
    description: "The matrix combined JSON outputs."
    value: ${{ steps.read-artifacts.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: prepare-download
      shell: bash
      run: |
        # Forge the unique artifact name for the current workflow
        ARTIFACT_NAME="${{ github.run_id }}-${{ github.run_number }}-${{ inputs.artifact-name }}"
        echo "artifact-name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

        ARTIFACT_PATH="/tmp/$ARTIFACT_NAME"
        echo "artifact-path=$ARTIFACT_PATH" >> "$GITHUB_OUTPUT"

    - uses: actions/download-artifact@v3
      with:
        name: ${{ steps.prepare-download.outputs.artifact-name }}
        path: ${{ steps.prepare-download.outputs.artifact-path }}

    - id: read-artifacts
      shell: bash
      run: |
        RESULT=$(jq -sc "." ${{ steps.prepare-download.outputs.artifact-path }}/*.json)
        echo "result<<EOF" >> "$GITHUB_OUTPUT" && echo "$RESULT" >> "$GITHUB_OUTPUT" && echo "EOF" >> "$GITHUB_OUTPUT"

    - if: ${{ inputs.remove-artifact == 'true' }}
      shell: bash
      run: rm -rf ${{ steps.prepare-download.outputs.artifact-path }}

    - if: ${{ inputs.remove-artifact == 'true' }}
      uses: geekyeggo/delete-artifact@v2
      with:
        name: ${{ steps.prepare-download.outputs.artifact-name }}
