name: "Parse CI Reports"
description: |
  Parse CI reports (tests, linting, coverage) into GitHub summary and Markdown for PR comments.
  This action parses various report formats from testing, linting, and coverage tools and generates:

  - GitHub Step Summaries for workflow runs
  - Markdown output suitable for pull request or issue comments
  - GitHub Annotations for failed tests and linting issues

  It supports multiple common report standards out of the box.
author: hoverkraft
branding:
  icon: check-circle
  color: blue

inputs:
  report-paths:
    description: |
      Paths to report files (glob patterns supported, one per line or comma-separated).
      Set to `auto:test`, `auto:coverage`, `auto:lint`, or `auto:all` for automatic detection.
      Examples: `**/junit.xml`, `coverage/lcov.info`, `eslint-report.json`, `auto:all`
    required: false
    default: "auto:all"
  report-name:
    description: |
      Name to display in the summary (e.g., `Test Results`, `Coverage Report`).
    default: "Report Summary"
  include-passed:
    description: |
      Whether to include passed tests in the summary.
    default: "false"
  output-format:
    description: |
      Output format: comma-separated list of `summary`, `markdown`, `annotations`, or `all` for everything.
    default: "all"
  fail-on-error:
    description: |
      Whether to fail the action if any test failures are detected.
    default: "false"
  path-mapping:
    description: |
      Path mapping to rewrite file paths in reports (format: "from_path:to_path").
      Useful when tests/lints run in a different directory or container.
      Example: "/app/src:./src" or "/var/lib/docker/.../app:."
    required: false
    default: ""

outputs:
  markdown:
    description: "Generated markdown output for PR comments"
    value: ${{ steps.parse-reports.outputs.markdown }}
  summary:
    description: "Generated summary output"
    value: ${{ steps.parse-reports.outputs.summary }}
  parsed-files:
    description: "List of parsed report files (JSON array)"
    value: ${{ steps.parse-reports.outputs.parsed-files }}
  has-errors:
    description: "Whether any errors were detected in the reports"
    value: ${{ steps.parse-reports.outputs.has-errors }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: hoverkraft-tech/ci-github-nodejs/actions/setup-node@32a69b7b8fd5f7ab7bf656e7e88aa90ad235cf8d # 0.18.0
      with:
        working-directory: ${{ github.action_path }}

    - name: Parse reports
      id: parse-reports
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        NODE_PATH: ${{ github.action_path }}/node_modules
        REPORT_PATHS: ${{ inputs.report-paths }}
        REPORT_NAME: ${{ inputs.report-name }}
        INCLUDE_PASSED: ${{ inputs.include-passed }}
        OUTPUT_FORMAT: ${{ inputs.output-format }}
        PATH_MAPPING: ${{ inputs.path-mapping }}
        ACTION_PATH: ${{ github.action_path }}
      with:
        script: |
          const path = require('path');
          const { run } = require(path.join(process.env.ACTION_PATH, 'src', 'index.js'));

          const inputs = {
            reportPaths: process.env.REPORT_PATHS,
            reportName: process.env.REPORT_NAME,
            includePassed: process.env.INCLUDE_PASSED === 'true',
            outputFormat: process.env.OUTPUT_FORMAT,
            pathMapping: process.env.PATH_MAPPING || null
          };

          await run({ core, glob, inputs });

    - name: Fail if errors detected
      if: inputs.fail-on-error == 'true' && steps.parse-reports.outputs.has-errors == 'true'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          core.setFailed('Test failures or errors detected in reports');
