# Workflow to greet new contributors.
# Mainly using [First Interaction Action](https://github.com/actions/first-interaction), with some opinionated defaults.
#
# - On issue creation, a comment is added to the issue.
# - On first contribution, a comment is added to the pull request.

name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    branches: [main]

  workflow_call:
    inputs:
      runs-on:
        description: |
          JSON array of runner(s) to use.
          See https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job.
        type: string
        default: '["ubuntu-latest"]'
        required: false
      issue_message:
        description: |
          Comment to post on an individual's first issue.
          See https://github.com/actions/first-interaction#usage.
        type: string
        required: false
        default: "Hi, thank for reporting an issue, we will check it out very soon"
      pr_message:
        description: |
          Comment to post on an individual's first pull request.
          See https://github.com/actions/first-interaction#usage.
        type: string
        default: "Hi, thank you for creating your PR, we will check it out very soon"
        required: false
    secrets:
      github-token:
        description: |
          Token for the repository.
          See https://github.com/actions/first-interaction#usage.
          Defaults to the GITHUB_TOKEN secret.

permissions: {}

jobs:
  greeting:
    runs-on: ${{ inputs.runs-on && fromJson(inputs.runs-on) || 'ubuntu-latest' }}
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
        with:
          repo_token: ${{ secrets.github-token || github.token }}
          issue_message: ${{ inputs.issue_message || 'Hi, thank for reporting an issue, we will check it out very soon' }}
          pr_message: ${{ inputs.pr_message || 'Hi, thank you for creating your PR, we will check it out very soon' }}
